### ISSUE TITLE
MSPhysics Control Panel blocking view of simulation

### ISSUE THREAD

**Issue by MrPrezident** [AntonSynytsia/MSPhysics#11]
Every time I hit play, the "MSPhysics Control Panel" pops up right in the middle of the screen blocking my view of the simulation. There is nothing actually on the control panel, so I really don't need that to pop up, and there doesn't seem to be any way to disable it or move it out of the way until after the simulation has already started, in which case it is too late, because the initial part of the simulation is the critical part. Even if I move the control panel out of the way, it will just pop up back in the middle of the screen again when I restart the simulation.

**Comment by MrPrezident** [comment]
FYI this is on Mac.

**Comment by AntonSynytsia** [comment]
Thanks for the report! I didn't had the chance to test MSPhysics on Mac. Until a new version is developed, you can turn off the control panel manually by disabling it. Comment out the following lines in simulation.rb (line 3317):
```ruby
if !MSPhysics::ControlPanel.open? && !AMS::IS_PLATFORM_WINDOWS
  MSPhysics::ControlPanel.open(true)
end
```
