### ISSUE TITLE
Question: What does the MS in MSPhysics stand for?

### ISSUE THREAD

**Issue by MrPrezident** [AntonSynytsia/MSPhysics#12]
The name MSPhysics reminds me too much of the name "MSPaint," but I doubt MS is supposed to stand for "Microsoft" here. I'm curious though. I couldn't find any explanation anywhere. Is it supposed to be an abbreviation for "Master of Science?"

**Comment by AntonSynytsia** [comment]
I actually don't know. It is just a great combination. When I first started writing it, I though naming it Math, Science, Physics and then My Sketchy Physics.
