### ISSUE TITLE
No tool tips on Mac

### ISSUE THREAD

**Issue by RichardBronosky** [AntonSynytsia/MSPhysics#2]
I'm not sure if this is an issue with MSPhysics or AMS Library, but the tools palettes don't behave like normal SketchUp palettes. There are no tool tips and the tools don't highlight to indicate that they are in use. It's very confusing for new users. Any ideas how we might debug and improve this?

**Comment by AntonSynytsia** [comment]
I think they work well on Windows. The Mac OS X side is unstable at the moment.

**Comment by RichardBronosky** [comment]
Well, it seems that they work when the toolbars are vertical but not horizontal. That is the same results I'm seeing out of other plugins. I guess we can close this one.

Note: switching between vertical and horizontal can be done by dragging the toolbar to the left edge or top edge of your screen respectively. You have to close and relaunch the app with vertical toolbars to get the tooltips to start working. So, thats: drag to left edge, close app, open app.
