### ISSUE TITLE
Updates for SketchUp 2019=>2022?

### ISSUE THREAD

**Issue by smokhov** [AntonSynytsia/MSPhysics#20]
Hi, any plans to update the official version of MSPhysics to SketchUp 2019?

**Comment by smokhov** [comment]
The extension works in 2017 and 2018, but some models require 2019, and MSPhysics, when installed in 2019, barfs out with errors and is unavailable... I am not sure how those people who tagged MSPhysics in the 3D Warehouse made their models work in 2019, unless they somehow recompiled the extension themselves...

**Comment by AntonSynytsia** [comment]
Hi. I will look into updating this for SU2019 in the following month. Try using it with SU2018 for now.

**Comment by leroycorbid** [comment]
Looking Forward to the update 

Thanx for a great addition to the application

**Comment by hltdev8642** [comment]
Anton (and smokhov), 
Good news is that I was able to get it working in SU 2019 relatively easily.

The error is due to a non-existent version 2.5 of the library file: `msp.lib.so` , and its corresponding directory in the plugins folder of Sketchup: `\MSPhysics\libraries\stage\win64\2.5\msp_lib.so`

I don't know if anything else was missing, however I simply cloned the master branch and extracted the entire contents of the MSPhysics folder into the old MSPhysics plugin directory and overwrote any files. 

So from the looks of it the fix would be as simple as updating the Sketchunation and SU Extension Warehouse resources to match this repository... As soon as the 2.5 folder and lib was added , it worked as usual with no errors so far. 

Added: `MSPhysics\RubyExtension\MSPhysics\libraries\stage\win64`**\2.5\msp_lib.so**

Hope that helps, if anyone is confused as to what I did let me know here id be happy to post more detailed instructions. (but basically just replace the plugin resources with the ones from this repo, or add the 2.5 folder and library at mimimum)

**Comment by AntonSynytsia** [comment]
@hltdev8642 Yes, the repository is compatible with SU2019 but this is a development version and has a number instability issues, multi-threading and joints in particular. I am planning to fix these issues before releasing a 2019 compatible version.

**Comment by hltdev8642** [comment]
Oh alright that makes sense! Thank you by the way for such a great plugin, it has been the bread and butter of my sketchup setup for a while now.

**Comment by cureter** [comment]
> Anton (and smokhov),
> Good news is that I was able to get it working in SU 2019 relatively easily.
> 
> The error is due to a non-existent version 2.5 of the library file: `msp.lib.so` , and its corresponding directory in the plugins folder of Sketchup: `\MSPhysics\libraries\stage\win64\2.5\msp_lib.so`
> 
> I don't know if anything else was missing, however I simply cloned the master branch and extracted the entire contents of the MSPhysics folder into the old MSPhysics plugin directory and overwrote any files.
> 
> So from the looks of it the fix would be as simple as updating the Sketchunation and SU Extension Warehouse resources to match this repository... As soon as the 2.5 folder and lib was added , it worked as usual with no errors so far.
> 
> Added: `MSPhysics\RubyExtension\MSPhysics\libraries\stage\win64`**\2.5\msp_lib.so**
> 
> Hope that helps, if anyone is confused as to what I did let me know here id be happy to post more detailed instructions. (but basically just replace the plugin resources with the ones from this repo, or add the 2.5 folder and library at mimimum)

Hi I know it's been over a year, but I think I've tried what you have listed. I couldn't get it to work. I get an error message:

```
Error Loading File C:/Users/cureter/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/MSPhysics/main_entry.rb

The requested module was not found.
C:/Users/cureter/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/MSPhysics/libraries/1.0.3/win64/2.5/msp_lib.so  ...
```

@AntonSynytsia thank you for developing this amazing plugin.

**Comment by ZionCorp** [comment]
Thank you very much for this plugin.

**Comment by marcelh-gh** [comment]
@AntonSynytsia is there any news on this? I would really love to use this great plugin with the current Sketchup Version 2021. A short info is much appreaciated, so I would know if I have to search for another solution. Thanks a lot!

**Comment by frontsi** [comment]
is there any news for sk2021 ? I just want to know it is complete  suspended  or it is going to be updated soon.
Thank you Anton.

**Comment by gkavboy** [comment]
It would be cool to use it on 2021 version... Voite +1

**Comment by nhafeng** [comment]
That's how I install MSPhysics in SU2019
go to Extension Manager,
install ams_Lib_v3.6.0h.rbz (newest version 3.7.1)
install MSPhysics_v1.0.3.rbz

copy newton.dll and 2.5/msp_lib.so to path:
C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2019\SketchUp\Plugins\MSPhysics\libraries\stage\win64

newton.dll and 2.5/msp_lib can be found in https://github.com/AntonSynytsia/MSPhysics/tree/master/RubyExtension/MSPhysics/libraries/stage/win64

**Comment by frontsi** [comment]
No didn't work out for Sketchup2021
is there a way for sk2021?

**Comment by frontsi** [comment]
Thanks,   I will try that way

**Comment by 2695429209** [comment]
> You can share the version you can use in 2019. It seems that the mobile version sent by RBZ to me is not good,

**Comment by nhafeng** [comment]
That's how I make MSPhysics work in SU2022.

*** You have to preinstall SU2019 beside SU2022 in the same computer. Without SU2019, It may show some failure message while SU2022 start up and not loading MSPhysics ***
*** I didn't test SU2020 or SU2021 to replace SU2019 mention above , may somebody have a try ***

go to Extension Manager,
install ams_Lib_v3.6.0h.rbz (newest version 3.7.1)
install MSPhysics_v1.0.3.rbz

Get the files from 
https://github.com/AntonSynytsia/MSPhysics/tree/anton-ver110
unzip and copy all files & folders to replace the old versions:

C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2022\SketchUp\Plugins

**Comment by nhafeng** [comment]
> > You can share the version you can use in 2019. It seems that the mobile version sent by RBZ to me is not good,

I dont know how to make .RBZ file actully.

**Comment by smokhov** [comment]
(just keeping the subject of the issue up-to-date :))

**Comment by bsikorsky** [comment]
> That's how I make MSPhysics work in SU2022.
> 
> *** You have to preinstall SU2019 beside SU2022 in the same computer. Without SU2019, It may show some failure message while SU2022 start up and not loading MSPhysics *** *** I didn't test SU2020 or SU2021 to replace SU2019 mention above , may somebody have a try ***
> 
> go to Extension Manager, install ams_Lib_v3.6.0h.rbz (newest version 3.7.1) install MSPhysics_v1.0.3.rbz
> 
> Get the files from https://github.com/AntonSynytsia/MSPhysics/tree/anton-ver110 unzip and copy all files & folders to replace the old versions:
> 
> C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2022\SketchUp\Plugins

Hi, could you explain more precisely whether you need to install SU2019 first and then SU2022? And which files should be copied and replaced?
Thank you

**Comment by nhafeng** [comment]
see https://github.com/AntonSynytsia/MSPhysics/issues/28#issuecomment-1344440040



***@***.***
 
From: bsikorsky
Date: 2023-02-13 19:41
To: AntonSynytsia/MSPhysics
CC: Leo Zhang; Comment
Subject: Re: [AntonSynytsia/MSPhysics] Updates for SketchUp 2019=>2022? (#20)
That's how I make MSPhysics work in SU2022.
*** You have to preinstall SU2019 beside SU2022 in the same computer. Without SU2019, It may show some failure message while SU2022 start up and not loading MSPhysics *** *** I didn't test SU2020 or SU2021 to replace SU2019 mention above , may somebody have a try ***
go to Extension Manager, install ams_Lib_v3.6.0h.rbz (newest version 3.7.1) install MSPhysics_v1.0.3.rbz
Get the files from https://github.com/AntonSynytsia/MSPhysics/tree/anton-ver110 unzip and copy all files & folders to replace the old versions:
C:\Users\user\AppData\Roaming\SketchUp\SketchUp 2022\SketchUp\Plugins
Hi, could you explain more precisely whether you need to install SU2019 first and then SU2022? And which files should be copied and replaced?
Thank you

**Comment by nurialibal** [comment]
I ran anton msphsics in sketchup 2021, but the control panel does not work because the control panel menu bar stays at the bottom of the screen and I can't interfere with the cure.

**Comment by smokhov** [comment]
@nhafeng maintains a more updated and recent issue #28 on this subject; I don't think we need two of them. One day @AntonSynytsia will awake and fix it or a proper fork will be made of it to keep up the maintenance... in the meantime I will close this :)

**Comment by Sparksyyy** [comment]
C:\Users\61466\3D Objects\The Super Magnetic Motor 3.skp

**Comment by Sparksyyy** [comment]
file://C:/Users/61466/OneDrive/Documents/MAGNETIC/MAGNETIC MOTOR COMPLETE 7.skp

**Comment by TalhaMWattoo** [comment]
[MSPhysics v1.1 Beta](https://forums.sketchup.com/uploads/short-url/xZRclAf91j3XRMqWGAX3vIVUJ2j.rbz)
This version works with most of the functions, some might not work. But works on SU 2022 and 2023.
