### ISSUE TITLE
`lefty` and `leftx` not working on Mac

### ISSUE THREAD

**Issue by RichardBronosky** [AntonSynytsia/MSPhysics#3]
Do lefty and leftx work on Mac? I keep getting taken out of Play mode when I hit A or S (which each activate the tool associated with the default keyboard shortcut) and W and D do nothing.

I am trying to follow this tutorial. https://youtu.be/U4eXsz1fi0M?t=138

**Comment by AntonSynytsia** [comment]
Yes, keyboard controls don't work on Mac OS X at the moment.

**Comment by RichardBronosky** [comment]
Is there anything you can think of that might allow me to control a Servo Joint? That's pretty critical for my project.

**Comment by AntonSynytsia** [comment]
You can use a slider controller instead. Open UI, select the servo joint, and click on the "generate slider controller" button and adjust the values afterwards.

**Comment by AntonSynytsia** [comment]
Hi, Richard,

Keyboard input, asside from events, should work now with 0.9.5.

Anton
