### ISSUE TITLE
Crash on Mac

### ISSUE THREAD

**Issue by ErmesTonelli** [AntonSynytsia/MSPhysics#4]
Good morning,
I installed MSPhysics 0.9.3 and AMS Library 3.3.0 on Mac 10.8.5, with Sketch Up 2015 Make, by Extension Warehouse.
Unfortunately it crashes if, once I clicked play, I try to move components with the mouse.
Where am I doing wrong??

**Comment by AntonSynytsia** [comment]
I haven't tested on mac 10.8.5, but I have tested it on OSX maverics

**Comment by AntonSynytsia** [comment]
Hi, Ermess,

Can you check if the crash occurs with the latest version, 0.9.5?

Thanks,
Anton
