### ISSUE TITLE
I can't open the tutorial drive

### ISSUE THREAD

**Issue by ParvanBoyukliev** [AntonSynytsia/MSPhysics#5]
I get the following message:

You need permission

Switch to an account with permission. Learn more

What do I need to do to get permission to view the tutorials?

**Comment by AntonSynytsia** [comment]
Hi, I relinked the link to tutorials by Samuel Ketner. Here it is: https://www.youtube.com/user/samketner/videos?sort=dd&view=0&shelf_id=0
