### ISSUE TITLE
serious bug regarding ui

### ISSUE THREAD

**Issue by electroscientistX** [AntonSynytsia/MSPhysics#6]
after enabling UI, i cant navigate in properties, scrypt, joints, sound i stuck in simulation tab(can input in simulation tab but unable to navigate in properties a d other tabs)
i tries it in SU 2016, SU 2017 but same issue

**Comment by AntonSynytsia** [comment]
You have to select a group prior to navigating to properties and script tabs.

**Comment by AntonSynytsia** [comment]
Are you using 0.9.8 and did you erase original version prior to downloading the new one (because it is important that you do).
