### ISSUE TITLE
Values not saving?

### ISSUE THREAD

**Issue by maxiedaniels** [AntonSynytsia/MSPhysics#7]
I'm on Mac. Often times when I put in a value (say, to change density, or a controller value), it won't save. If I click on another field and then click on the original field again, it'll revert to the last value. The only way I can get it to change is to keep typing in the value, clicking off and on again, and repeating... it seems to finally change after 5-10 attempts.

**Comment by AntonSynytsia** [comment]
Thanks for reporting, maxiedaniels. I'll check it out.

**Comment by AntonSynytsia** [comment]
Try out 0.9.9. Perhaps it's fixed now.
