### ISSUE TITLE
The size of the joins, motors etc.

### ISSUE THREAD

**Issue by diogobr** [AntonSynytsia/MSPhysics#9]
When I use other projects in my new project, the sise of joins don't follow my new project size. And they stay the same proportion when i change the size of all joints. Please, solve this problem.

**Comment by AntonSynytsia** [comment]
The size of joints should stay the same unless you manually scaled them, which will affect the scale ratios.

**Comment by diogobr** [comment]
Yes, but this makes me crazy because I use models from 3dwarehouse and I can't to manually scale all because is too much joins. I need a way to make all the same size again in the same time. Because all time i need to open the joins in a new project only to change their scale. Thank you.
